# Generated by Django 5.2.6 on 2025-11-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('categorie', models.CharField(choices=[('DEVOIRS', 'Devoirs'), ('STATISTIQUES', 'Statistiques'), ('ECONOMIE', 'Économie'), ('OUTILS', 'Outils'), ('ETUDES_CAS', 'Études de Cas')], max_length=20)),
                ('niveau', models.CharField(choices=[('DEBUTANT', 'Débutant'), ('INTERMEDIAIRE', 'Intermédiaire'), ('AVANCE', 'Avancé')], max_length=20)),
                ('fichier', models.FileField(upload_to='ressources/')),
                ('taille_fichier', models.CharField(blank=True, max_length=50)),
                ('accessible_vip', models.BooleanField(default=False)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('echeance', models.DateField(blank=True, null=True)),
                ('duree_estimee', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
            },
        ),
    ]
