# Generated by Django 5.2.6 on 2026-01-15 02:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0002_formation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_transactions', models.IntegerField(default=0)),
                ('successful_transactions', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('by_operator', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SMSParserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_content', models.TextField()),
                ('sender', models.CharField(max_length=15)),
                ('parser_used', models.CharField(max_length=50)),
                ('parsed_data', models.JSONField()),
                ('is_success', models.BooleanField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAutoConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user_phone', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operator', models.CharField(choices=[('orange', 'Orange Money'), ('moov', 'Moov Money'), ('wave', 'Wave')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.formation')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('reference_code', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=200)),
                ('user_phone', models.CharField(max_length=15)),
                ('user_email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operator', models.CharField(choices=[('orange', 'Orange Money'), ('moov', 'Moov Money'), ('wave', 'Wave')], max_length=20)),
                ('recipient_phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('completed', 'Complétée'), ('failed', 'Échouée'), ('expired', 'Expirée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('sms_content', models.TextField(blank=True, null=True)),
                ('sms_sender', models.CharField(blank=True, max_length=15, null=True)),
                ('sms_timestamp', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formations.formation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='paiements_t_transac_91a070_idx'), models.Index(fields=['user_phone'], name='paiements_t_user_ph_c861c4_idx'), models.Index(fields=['status'], name='paiements_t_status_c4783b_idx'), models.Index(fields=['created_at'], name='paiements_t_created_576a3e_idx')],
            },
        ),
    ]
