# Generated by Django 5.2.6 on 2025-11-14 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonnementVIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_abonnement', models.CharField(choices=[('gratuit', 'Gratuit'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=20)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_annuel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField()),
                ('avantages', models.TextField(help_text='Séparez les avantages par des points-virgules')),
                ('est_populaire', models.BooleanField(default=False)),
                ('couleur_principale', models.CharField(default='#3B82F6', max_length=7)),
                ('ordre_affichage', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Abonnement VIP',
                'verbose_name_plural': 'Abonnements VIP',
                'ordering': ['ordre_affichage', 'prix'],
            },
        ),
        migrations.CreateModel(
            name='CategorieActualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategorieFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='formateurs/')),
            ],
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('devoirs', 'Devoirs'), ('outils', 'Outils Statistiques'), ('bibliotheque', 'Bibliothèque'), ('performances', 'Performances'), ('economique', 'Données Économiques'), ('corrections', 'Corrections')], max_length=20)),
                ('fichier', models.FileField(upload_to='ressources/')),
                ('description', models.TextField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActiviteMembre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_activite', models.CharField(choices=[('devoir_corrige', 'Devoir Corrigé'), ('nouvelle_formation', 'Nouvelle Formation'), ('rappel_devoir', 'Rappel Devoir'), ('certification_obtenue', 'Certification Obtenue'), ('progression', 'Progression'), ('annonce', 'Annonce')], max_length=30)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_activite', models.DateTimeField(auto_now_add=True)),
                ('lien', models.URLField(blank=True, null=True)),
                ('est_lue', models.BooleanField(default=False)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activité Membre',
                'verbose_name_plural': 'Activités Membres',
                'ordering': ['-date_activite'],
            },
        ),
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='actualites/')),
                ('auteur', models.CharField(max_length=100)),
                ('vues', models.IntegerField(default=0)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categorieactualite')),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_evenement', models.DateTimeField()),
                ('lieu', models.CharField(max_length=100)),
                ('formateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.formateur')),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], max_length=20)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('lien_inscription', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='formations/')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categorieformation')),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.formateur')),
            ],
        ),
        migrations.CreateModel(
            name='GalerieImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='galerie/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('evenement_lie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.evenement')),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='ProfilMembre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_etudiant', models.CharField(max_length=20, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('niveau_academique', models.CharField(choices=[('licence1', 'Licence 1'), ('licence2', 'Licence 2'), ('licence3', 'Licence 3'), ('master1', 'Master 1'), ('master2', 'Master 2'), ('doctorat', 'Doctorat')], max_length=20)),
                ('specialisation', models.CharField(choices=[('statistics', 'Statistiques'), ('economics', 'Économie'), ('econometrics', 'Économétrie'), ('data-science', 'Science des Données'), ('applied-economics', 'Économie Appliquée'), ('financial-economics', 'Économie Financière'), ('mathematiques', 'Mathématiques')], max_length=30)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('est_vip', models.BooleanField(default=False)),
                ('date_fin_vip', models.DateField(blank=True, null=True)),
                ('newsletter_acceptee', models.BooleanField(default=False)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TemoignageVIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('note', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_approuve', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Témoignage VIP',
                'verbose_name_plural': 'Témoignages VIP',
                'ordering': ['-date_creation'],
            },
        ),
    ]
