# Generated by Django 5.2.6 on 2025-11-30 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profilmembre_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evenement',
            options={'permissions': [('can_publish_evenement', 'Can publish evenement'), ('can_manage_evenement', 'Can manage evenement')]},
        ),
    ]
