# Generated by Django 5.2.6 on 2025-11-30 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_evenement_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evenement',
            old_name='date_evenement',
            new_name='date_debut',
        ),
    ]
