# Generated by Django 5.2.6 on 2025-11-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_date_evenement_evenement_date_debut'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='est_publie',
            field=models.BooleanField(default=True, verbose_name='Est publié'),
        ),
        migrations.AddField(
            model_name='actualite',
            name='type_actualite',
            field=models.CharField(choices=[('FEATURED', 'À la une'), ('NORMAL', 'Normal')], default='NORMAL', max_length=20, verbose_name="Type d'actualité"),
        ),
        migrations.AddField(
            model_name='evenement',
            name='est_actif',
            field=models.BooleanField(default=True, verbose_name='Est actif'),
        ),
    ]
