# Generated by Django 5.2.6 on 2025-11-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_actualite_est_publie_actualite_type_actualite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='resume',
            field=models.TextField(blank=True, help_text="Résumé court pour l'affichage dans les listes", max_length=300),
        ),
    ]
