# Generated by Django 5.2.6 on 2025-12-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_actualite_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('formation_nom', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_phone', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('operator', models.CharField(choices=[('orange', 'Orange Money'), ('moov', 'Moov Money')], max_length=10)),
                ('operator_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('rejected', 'Rejeté'), ('expired', 'Expiré')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('sms_sender', models.CharField(blank=True, max_length=20)),
                ('sms_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sms_code', models.CharField(blank=True, max_length=10)),
                ('sms_received_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='main_paieme_transac_f4b721_idx'), models.Index(fields=['status'], name='main_paieme_status_6fdd49_idx'), models.Index(fields=['created_at'], name='main_paieme_created_da3406_idx')],
            },
        ),
    ]
