# Generated by Django 5.2.6 on 2025-12-02 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_service', models.CharField(choices=[('formation', 'Formation'), ('abonnement', 'Abonnement VIP'), ('vip', 'Membre VIP'), ('ressource', 'Ressource Premium')], max_length=20)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('duree_jours', models.IntegerField(default=30, help_text='Durée en jours')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['type_service', 'prix'],
            },
        ),
        migrations.AlterModelOptions(
            name='paiement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='formation_nom',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='sms_amount',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='sms_code',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='sms_received_at',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='sms_sender',
        ),
        migrations.AddField(
            model_name='paiement',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='Notes admin'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Traité'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='reference_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Code de référence'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='sms_received',
            field=models.TextField(blank=True, verbose_name='SMS reçu'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date confirmation'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date création'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (FCFA)'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='operator',
            field=models.CharField(choices=[('orange', 'Orange Money'), ('moov', 'Moov Money')], max_length=10, verbose_name='Opérateur'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='operator_number',
            field=models.CharField(default='', max_length=20, verbose_name='Numéro opérateur'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ En attente'), ('confirmed', '✅ Confirmé'), ('rejected', '❌ Rejeté'), ('expired', '⌛ Expiré')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date soumission'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='transaction_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='ID Transaction'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='user_email',
            field=models.EmailField(max_length=254, verbose_name='Email utilisateur'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='user_name',
            field=models.CharField(max_length=100, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='user_phone',
            field=models.CharField(max_length=20, verbose_name='Téléphone utilisateur'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.service', verbose_name='Service'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['user_phone'], name='main_paieme_user_ph_4c1b89_idx'),
        ),
    ]
