# Generated by Django 5.2.6 on 2025-12-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_service_alter_paiement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorieactualite',
            options={'ordering': ['ordre', 'nom'], 'verbose_name': "Catégorie d'Actualité", 'verbose_name_plural': "Catégories d'Actualité"},
        ),
        migrations.AddField(
            model_name='categorieactualite',
            name='couleur',
            field=models.CharField(default='bg-primary-100 text-primary-600', max_length=50),
        ),
        migrations.AddField(
            model_name='categorieactualite',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='categorieactualite',
            name='icone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='categorieactualite',
            name='ordre',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categorieactualite',
            name='type_categorie',
            field=models.CharField(blank=True, choices=[('TOUTES', 'Toutes les actualités'), ('FORMATIONS', 'Formations'), ('REUSSITES', 'Réussites'), ('EVENEMENTS', 'Événements'), ('PARTENARIATS', 'Partenariats'), ('ANNONCE', 'Annonce')], max_length=20, null=True, unique=True),
        ),
    ]
