# Generated by Django 5.2.6 on 2026-01-15 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_categorieactualite_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InscriptionFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=15)),
                ('nom', models.CharField(max_length=200)),
                ('statut', models.CharField(choices=[('pending', 'En attente de paiement'), ('completed', 'Inscription complétée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('reference_code', models.CharField(blank=True, max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_completion', models.DateTimeField(blank=True, null=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='main.formation')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_formations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_inscription'],
                'unique_together': {('email', 'formation')},
            },
        ),
    ]
