# Generated by Django 5.2.6 on 2026-01-15 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0002_formation'),
        ('main', '0010_inscriptionformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptionformation',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='formations.formation'),
        ),
    ]
