# Generated by Django 5.2.6 on 2025-11-13 22:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieActualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('couleur', models.CharField(default='bg-primary-100 text-primary-600', max_length=50)),
                ('icone', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('lieu', models.CharField(max_length=200)),
                ('formateur', models.CharField(blank=True, max_length=100)),
                ('couleur', models.CharField(default='border-secondary', max_length=50)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ReussiteMembre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='reussites/')),
                ('photo_url', models.URLField(blank=True)),
                ('realisation', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type_reussite', models.CharField(blank=True, max_length=100)),
                ('date_reussite', models.DateField(default=django.utils.timezone.now)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Réussite Membre',
                'verbose_name_plural': 'Réussites Membres',
                'ordering': ['-date_reussite'],
            },
        ),
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('resume', models.TextField(blank=True)),
                ('type_actualite', models.CharField(choices=[('FEATURED', 'À la une'), ('REGULAR', 'Régulière')], default='REGULAR', max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='actualites/')),
                ('image_url', models.URLField(blank=True)),
                ('auteur', models.CharField(blank=True, max_length=100)),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('vues', models.IntegerField(default=0)),
                ('est_publie', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('meta_titre', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actualites.categorieactualite')),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-date_publication'],
            },
        ),
    ]
