# Generated by Django 5.2.6 on 2025-12-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorieactualite',
            options={'ordering': ['ordre', 'nom'], 'verbose_name': "Catégorie d'Actualité", 'verbose_name_plural': "Catégories d'Actualité"},
        ),
        migrations.AddField(
            model_name='categorieactualite',
            name='ordre',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categorieactualite',
            name='type_categorie',
            field=models.CharField(choices=[('TOUTES', 'Toutes les actualités'), ('FORMATIONS', 'Formations'), ('REUSSITES', 'Réussites'), ('EVENEMENTS', 'Événements'), ('PARTENARIATS', 'Partenariats'), ('ANNONCE', 'Annonce'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20),
        ),
    ]
