# Generated by Django 5.2.6 on 2025-12-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0002_alter_categorieactualite_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorieactualite',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='categorieactualite',
            name='type_categorie',
            field=models.CharField(choices=[('TOUTES', 'Toutes les actualités'), ('FORMATIONS', 'Formations'), ('REUSSITES', 'Réussites'), ('EVENEMENTS', 'Événements'), ('PARTENARIATS', 'Partenariats'), ('ANNONCE', 'Annonce')], max_length=20, unique=True),
        ),
    ]
