# Generated by Django 5.2.6 on 2025-12-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0003_categorieactualite_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorieactualite',
            name='type_categorie',
            field=models.CharField(choices=[('FORMATIONS', 'Formations'), ('REUSSITES', 'Réussites'), ('EVENEMENTS', 'Événements'), ('PARTENARIATS', 'Partenariats'), ('ANNONCE', 'Announce')], max_length=20, unique=True),
        ),
    ]
