# Generated by Django 5.2.6 on 2026-01-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0004_alter_categorieactualite_type_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorieactualite',
            name='type_categorie',
            field=models.CharField(choices=[('TOUTES', 'Toutes les actualités'), ('FORMATIONS', 'Formations'), ('REUSSITES', 'Réussites'), ('EVENEMENTS', 'Événements'), ('PARTENARIATS', 'Partenariats'), ('ANNONCE', 'Annonce')], max_length=20, unique=True),
        ),
    ]
