# Generated by Django 5.2.6 on 2025-11-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('bio', models.TextField(verbose_name='Biographie')),
                ('photo', models.ImageField(upload_to='formateurs/', verbose_name='Photo de profil')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('specialite', models.CharField(max_length=100, verbose_name='Spécialité')),
            ],
            options={
                'verbose_name': 'Formateur',
                'verbose_name_plural': 'Formateurs',
            },
        ),
    ]
