# Generated by Django 5.2.6 on 2025-11-07 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de la formation')),
                ('description', models.TextField(verbose_name='Description')),
                ('niveau', models.CharField(choices=[('DEBUTANT', 'Débutant'), ('INTERMEDIAIRE', 'Intermédiaire'), ('AVANCE', 'Avancé')], max_length=20, verbose_name='Niveau')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (€)')),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(verbose_name='Date de fin')),
                ('lien_inscription', models.URLField(verbose_name="Lien d'inscription")),
                ('image', models.ImageField(upload_to='formations/', verbose_name='Image de la formation')),
                ('duree', models.CharField(help_text='Ex: 4 semaines, 2 mois', max_length=50, verbose_name='Durée')),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.formateur', verbose_name='Formateur')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['-date_debut'],
            },
        ),
    ]
